//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.14.0
//     from Assets/InputActions/GameInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/InputActions/GameInputActions.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @GameInputActions: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @GameInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""GameInputActions"",
    ""maps"": [
        {
            ""name"": ""BattleActions"",
            ""id"": ""ad536389-45ca-4cdb-b882-5f8ad8be7f12"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""b9a830c8-328b-4a73-9487-9cb928c48e0d"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Pass"",
                    ""type"": ""Button"",
                    ""id"": ""50954c03-8e00-4f8c-ab05-4a1b9e0f1226"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Shoot"",
                    ""type"": ""Button"",
                    ""id"": ""26e9f961-aa4f-43b2-93b0-55830add8634"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Change"",
                    ""type"": ""Button"",
                    ""id"": ""82ce4dd3-18c4-44aa-b9d7-314c523ce5a2"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Dribble"",
                    ""type"": ""Button"",
                    ""id"": ""c23afaae-ffaa-4389-b20d-4a52ab6b9313"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Block"",
                    ""type"": ""Button"",
                    ""id"": ""0982b186-8e81-4ec8-b9f1-b8edf5546457"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""44b9b154-61d7-4748-a5b6-c75b3c19a6b9"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""ebb18c77-62b2-4774-a0b8-ca61daf03b95"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""321c8ffe-4ca8-43f6-b88b-f33e99d9c6dd"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""d32739f9-8a32-48d0-acd6-7df1e6242194"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""bee0adc4-33fe-4ac2-a353-0ddec716ceee"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""06a561b2-5f5b-4553-b939-65e880bc3274"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""345f4b4c-5557-43f7-8626-78d85f557324"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pass"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""271d7cbf-8b87-484e-99f2-3a3f2b1f84bb"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pass"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a94bfe7c-3b85-4769-a7a7-f6bd246eb44b"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Shoot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""790dee7f-7e87-4951-8617-db3de9f1334f"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Shoot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b25c26c8-8884-4b62-acc9-fc7c2c7abb8d"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Change"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6e71530c-bbeb-4e66-b22e-94513a93dadc"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Change"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dfc16283-b872-4855-aa7d-c7344ac4c533"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dribble"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""796d6014-e6b0-4e26-8aba-2685bf803bfc"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dribble"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""58384ce6-b67e-4837-a218-5ce78626d315"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Block"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a1e67e1d-b067-4aef-8a94-b6ec3a1efa2b"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Block"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""BattleUIActions"",
            ""id"": ""3aecf937-1126-4c9f-b798-e8d2138111c2"",
            ""actions"": [
                {
                    ""name"": ""BattleUI_ClickEastButton"",
                    ""type"": ""Button"",
                    ""id"": ""457a3649-823d-4c07-873a-a6d717d6c0fe"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""BattleUI_ClickWestButton"",
                    ""type"": ""Button"",
                    ""id"": ""10507b5e-673d-4aa6-af68-fa8e64e76d8d"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""BattleUI_ClickNorthButton"",
                    ""type"": ""Button"",
                    ""id"": ""a467c15b-a758-4d8f-b3dc-074143206a95"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""BattleUI_ClickSouthButton"",
                    ""type"": ""Button"",
                    ""id"": ""22842503-685e-4740-9530-a775d1c910e1"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""BattleUI_CloseMoveMenu"",
                    ""type"": ""Button"",
                    ""id"": ""cd23d3cb-5a26-45f9-93af-dfba74178af4"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""BattleUI_NextMove"",
                    ""type"": ""Button"",
                    ""id"": ""fcea7f93-1247-460a-9c15-7967a03281be"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""BattleUI_OpenBattleMenu"",
                    ""type"": ""Button"",
                    ""id"": ""4a8bb965-7f19-45e9-a325-8857a002c664"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""BattleUI_CloseBattleMenu"",
                    ""type"": ""Button"",
                    ""id"": ""905ba53f-3f3d-4a83-a818-b9b564d0ed42"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""BattleUI_BattleMenuShortcutPause"",
                    ""type"": ""Button"",
                    ""id"": ""e54f6eb6-18ce-47d6-9f52-cc0d5ccbca35"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""47b01c18-99ba-4de0-a75a-43162f50b863"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BattleUI_ClickEastButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1a871c8c-18f7-4557-9a5d-57fb8accef79"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BattleUI_ClickEastButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3a911e05-b7ea-4a25-826e-a97ab8e6bfc6"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BattleUI_ClickWestButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a47857f9-780d-40c3-8edd-8158e1c79d9f"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BattleUI_ClickWestButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""584ae5ab-f7f8-41b7-b13c-6205caf3a670"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BattleUI_ClickNorthButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""255cf56a-1495-41a1-98a8-a36b2dc9aaf7"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BattleUI_ClickNorthButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c075df0a-62d4-4294-ba49-9a9103c92ad1"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BattleUI_NextMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5ddc2800-49ab-4149-8797-abe946770ee2"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BattleUI_NextMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2c23302d-70fd-4b58-896c-4a50d1f5831e"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BattleUI_CloseMoveMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""24c76f65-afe1-49e3-a7a8-d4cc8a4f2f0c"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BattleUI_CloseMoveMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ed0a0c9e-567b-479e-8dff-9fcaf4e6e795"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BattleUI_ClickSouthButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0a36d5af-20d0-47ba-8fcf-db36a0489cd0"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BattleUI_OpenBattleMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""45653903-ab53-403e-952f-aff97a6fcd01"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BattleUI_OpenBattleMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b9dc8e5f-850d-4b10-add7-21b3b7f3b4c3"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BattleUI_CloseBattleMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""04c5c765-f851-49d3-9ee6-7e0d46387fa8"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BattleUI_CloseBattleMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6a0a74c7-9b7d-4e42-87c0-e2d2fb1d725b"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BattleUI_CloseBattleMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a3c805a0-813f-4fb6-abd5-9f2251a1cbec"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BattleUI_BattleMenuShortcutPause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // BattleActions
        m_BattleActions = asset.FindActionMap("BattleActions", throwIfNotFound: true);
        m_BattleActions_Move = m_BattleActions.FindAction("Move", throwIfNotFound: true);
        m_BattleActions_Pass = m_BattleActions.FindAction("Pass", throwIfNotFound: true);
        m_BattleActions_Shoot = m_BattleActions.FindAction("Shoot", throwIfNotFound: true);
        m_BattleActions_Change = m_BattleActions.FindAction("Change", throwIfNotFound: true);
        m_BattleActions_Dribble = m_BattleActions.FindAction("Dribble", throwIfNotFound: true);
        m_BattleActions_Block = m_BattleActions.FindAction("Block", throwIfNotFound: true);
        // BattleUIActions
        m_BattleUIActions = asset.FindActionMap("BattleUIActions", throwIfNotFound: true);
        m_BattleUIActions_BattleUI_ClickEastButton = m_BattleUIActions.FindAction("BattleUI_ClickEastButton", throwIfNotFound: true);
        m_BattleUIActions_BattleUI_ClickWestButton = m_BattleUIActions.FindAction("BattleUI_ClickWestButton", throwIfNotFound: true);
        m_BattleUIActions_BattleUI_ClickNorthButton = m_BattleUIActions.FindAction("BattleUI_ClickNorthButton", throwIfNotFound: true);
        m_BattleUIActions_BattleUI_ClickSouthButton = m_BattleUIActions.FindAction("BattleUI_ClickSouthButton", throwIfNotFound: true);
        m_BattleUIActions_BattleUI_CloseMoveMenu = m_BattleUIActions.FindAction("BattleUI_CloseMoveMenu", throwIfNotFound: true);
        m_BattleUIActions_BattleUI_NextMove = m_BattleUIActions.FindAction("BattleUI_NextMove", throwIfNotFound: true);
        m_BattleUIActions_BattleUI_OpenBattleMenu = m_BattleUIActions.FindAction("BattleUI_OpenBattleMenu", throwIfNotFound: true);
        m_BattleUIActions_BattleUI_CloseBattleMenu = m_BattleUIActions.FindAction("BattleUI_CloseBattleMenu", throwIfNotFound: true);
        m_BattleUIActions_BattleUI_BattleMenuShortcutPause = m_BattleUIActions.FindAction("BattleUI_BattleMenuShortcutPause", throwIfNotFound: true);
    }

    ~@GameInputActions()
    {
        UnityEngine.Debug.Assert(!m_BattleActions.enabled, "This will cause a leak and performance issues, GameInputActions.BattleActions.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_BattleUIActions.enabled, "This will cause a leak and performance issues, GameInputActions.BattleUIActions.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // BattleActions
    private readonly InputActionMap m_BattleActions;
    private List<IBattleActionsActions> m_BattleActionsActionsCallbackInterfaces = new List<IBattleActionsActions>();
    private readonly InputAction m_BattleActions_Move;
    private readonly InputAction m_BattleActions_Pass;
    private readonly InputAction m_BattleActions_Shoot;
    private readonly InputAction m_BattleActions_Change;
    private readonly InputAction m_BattleActions_Dribble;
    private readonly InputAction m_BattleActions_Block;
    /// <summary>
    /// Provides access to input actions defined in input action map "BattleActions".
    /// </summary>
    public struct BattleActionsActions
    {
        private @GameInputActions m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public BattleActionsActions(@GameInputActions wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "BattleActions/Move".
        /// </summary>
        public InputAction @Move => m_Wrapper.m_BattleActions_Move;
        /// <summary>
        /// Provides access to the underlying input action "BattleActions/Pass".
        /// </summary>
        public InputAction @Pass => m_Wrapper.m_BattleActions_Pass;
        /// <summary>
        /// Provides access to the underlying input action "BattleActions/Shoot".
        /// </summary>
        public InputAction @Shoot => m_Wrapper.m_BattleActions_Shoot;
        /// <summary>
        /// Provides access to the underlying input action "BattleActions/Change".
        /// </summary>
        public InputAction @Change => m_Wrapper.m_BattleActions_Change;
        /// <summary>
        /// Provides access to the underlying input action "BattleActions/Dribble".
        /// </summary>
        public InputAction @Dribble => m_Wrapper.m_BattleActions_Dribble;
        /// <summary>
        /// Provides access to the underlying input action "BattleActions/Block".
        /// </summary>
        public InputAction @Block => m_Wrapper.m_BattleActions_Block;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_BattleActions; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="BattleActionsActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(BattleActionsActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="BattleActionsActions" />
        public void AddCallbacks(IBattleActionsActions instance)
        {
            if (instance == null || m_Wrapper.m_BattleActionsActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_BattleActionsActionsCallbackInterfaces.Add(instance);
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
            @Pass.started += instance.OnPass;
            @Pass.performed += instance.OnPass;
            @Pass.canceled += instance.OnPass;
            @Shoot.started += instance.OnShoot;
            @Shoot.performed += instance.OnShoot;
            @Shoot.canceled += instance.OnShoot;
            @Change.started += instance.OnChange;
            @Change.performed += instance.OnChange;
            @Change.canceled += instance.OnChange;
            @Dribble.started += instance.OnDribble;
            @Dribble.performed += instance.OnDribble;
            @Dribble.canceled += instance.OnDribble;
            @Block.started += instance.OnBlock;
            @Block.performed += instance.OnBlock;
            @Block.canceled += instance.OnBlock;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="BattleActionsActions" />
        private void UnregisterCallbacks(IBattleActionsActions instance)
        {
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
            @Pass.started -= instance.OnPass;
            @Pass.performed -= instance.OnPass;
            @Pass.canceled -= instance.OnPass;
            @Shoot.started -= instance.OnShoot;
            @Shoot.performed -= instance.OnShoot;
            @Shoot.canceled -= instance.OnShoot;
            @Change.started -= instance.OnChange;
            @Change.performed -= instance.OnChange;
            @Change.canceled -= instance.OnChange;
            @Dribble.started -= instance.OnDribble;
            @Dribble.performed -= instance.OnDribble;
            @Dribble.canceled -= instance.OnDribble;
            @Block.started -= instance.OnBlock;
            @Block.performed -= instance.OnBlock;
            @Block.canceled -= instance.OnBlock;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="BattleActionsActions.UnregisterCallbacks(IBattleActionsActions)" />.
        /// </summary>
        /// <seealso cref="BattleActionsActions.UnregisterCallbacks(IBattleActionsActions)" />
        public void RemoveCallbacks(IBattleActionsActions instance)
        {
            if (m_Wrapper.m_BattleActionsActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="BattleActionsActions.AddCallbacks(IBattleActionsActions)" />
        /// <seealso cref="BattleActionsActions.RemoveCallbacks(IBattleActionsActions)" />
        /// <seealso cref="BattleActionsActions.UnregisterCallbacks(IBattleActionsActions)" />
        public void SetCallbacks(IBattleActionsActions instance)
        {
            foreach (var item in m_Wrapper.m_BattleActionsActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_BattleActionsActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="BattleActionsActions" /> instance referencing this action map.
    /// </summary>
    public BattleActionsActions @BattleActions => new BattleActionsActions(this);

    // BattleUIActions
    private readonly InputActionMap m_BattleUIActions;
    private List<IBattleUIActionsActions> m_BattleUIActionsActionsCallbackInterfaces = new List<IBattleUIActionsActions>();
    private readonly InputAction m_BattleUIActions_BattleUI_ClickEastButton;
    private readonly InputAction m_BattleUIActions_BattleUI_ClickWestButton;
    private readonly InputAction m_BattleUIActions_BattleUI_ClickNorthButton;
    private readonly InputAction m_BattleUIActions_BattleUI_ClickSouthButton;
    private readonly InputAction m_BattleUIActions_BattleUI_CloseMoveMenu;
    private readonly InputAction m_BattleUIActions_BattleUI_NextMove;
    private readonly InputAction m_BattleUIActions_BattleUI_OpenBattleMenu;
    private readonly InputAction m_BattleUIActions_BattleUI_CloseBattleMenu;
    private readonly InputAction m_BattleUIActions_BattleUI_BattleMenuShortcutPause;
    /// <summary>
    /// Provides access to input actions defined in input action map "BattleUIActions".
    /// </summary>
    public struct BattleUIActionsActions
    {
        private @GameInputActions m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public BattleUIActionsActions(@GameInputActions wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "BattleUIActions/BattleUI_ClickEastButton".
        /// </summary>
        public InputAction @BattleUI_ClickEastButton => m_Wrapper.m_BattleUIActions_BattleUI_ClickEastButton;
        /// <summary>
        /// Provides access to the underlying input action "BattleUIActions/BattleUI_ClickWestButton".
        /// </summary>
        public InputAction @BattleUI_ClickWestButton => m_Wrapper.m_BattleUIActions_BattleUI_ClickWestButton;
        /// <summary>
        /// Provides access to the underlying input action "BattleUIActions/BattleUI_ClickNorthButton".
        /// </summary>
        public InputAction @BattleUI_ClickNorthButton => m_Wrapper.m_BattleUIActions_BattleUI_ClickNorthButton;
        /// <summary>
        /// Provides access to the underlying input action "BattleUIActions/BattleUI_ClickSouthButton".
        /// </summary>
        public InputAction @BattleUI_ClickSouthButton => m_Wrapper.m_BattleUIActions_BattleUI_ClickSouthButton;
        /// <summary>
        /// Provides access to the underlying input action "BattleUIActions/BattleUI_CloseMoveMenu".
        /// </summary>
        public InputAction @BattleUI_CloseMoveMenu => m_Wrapper.m_BattleUIActions_BattleUI_CloseMoveMenu;
        /// <summary>
        /// Provides access to the underlying input action "BattleUIActions/BattleUI_NextMove".
        /// </summary>
        public InputAction @BattleUI_NextMove => m_Wrapper.m_BattleUIActions_BattleUI_NextMove;
        /// <summary>
        /// Provides access to the underlying input action "BattleUIActions/BattleUI_OpenBattleMenu".
        /// </summary>
        public InputAction @BattleUI_OpenBattleMenu => m_Wrapper.m_BattleUIActions_BattleUI_OpenBattleMenu;
        /// <summary>
        /// Provides access to the underlying input action "BattleUIActions/BattleUI_CloseBattleMenu".
        /// </summary>
        public InputAction @BattleUI_CloseBattleMenu => m_Wrapper.m_BattleUIActions_BattleUI_CloseBattleMenu;
        /// <summary>
        /// Provides access to the underlying input action "BattleUIActions/BattleUI_BattleMenuShortcutPause".
        /// </summary>
        public InputAction @BattleUI_BattleMenuShortcutPause => m_Wrapper.m_BattleUIActions_BattleUI_BattleMenuShortcutPause;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_BattleUIActions; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="BattleUIActionsActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(BattleUIActionsActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="BattleUIActionsActions" />
        public void AddCallbacks(IBattleUIActionsActions instance)
        {
            if (instance == null || m_Wrapper.m_BattleUIActionsActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_BattleUIActionsActionsCallbackInterfaces.Add(instance);
            @BattleUI_ClickEastButton.started += instance.OnBattleUI_ClickEastButton;
            @BattleUI_ClickEastButton.performed += instance.OnBattleUI_ClickEastButton;
            @BattleUI_ClickEastButton.canceled += instance.OnBattleUI_ClickEastButton;
            @BattleUI_ClickWestButton.started += instance.OnBattleUI_ClickWestButton;
            @BattleUI_ClickWestButton.performed += instance.OnBattleUI_ClickWestButton;
            @BattleUI_ClickWestButton.canceled += instance.OnBattleUI_ClickWestButton;
            @BattleUI_ClickNorthButton.started += instance.OnBattleUI_ClickNorthButton;
            @BattleUI_ClickNorthButton.performed += instance.OnBattleUI_ClickNorthButton;
            @BattleUI_ClickNorthButton.canceled += instance.OnBattleUI_ClickNorthButton;
            @BattleUI_ClickSouthButton.started += instance.OnBattleUI_ClickSouthButton;
            @BattleUI_ClickSouthButton.performed += instance.OnBattleUI_ClickSouthButton;
            @BattleUI_ClickSouthButton.canceled += instance.OnBattleUI_ClickSouthButton;
            @BattleUI_CloseMoveMenu.started += instance.OnBattleUI_CloseMoveMenu;
            @BattleUI_CloseMoveMenu.performed += instance.OnBattleUI_CloseMoveMenu;
            @BattleUI_CloseMoveMenu.canceled += instance.OnBattleUI_CloseMoveMenu;
            @BattleUI_NextMove.started += instance.OnBattleUI_NextMove;
            @BattleUI_NextMove.performed += instance.OnBattleUI_NextMove;
            @BattleUI_NextMove.canceled += instance.OnBattleUI_NextMove;
            @BattleUI_OpenBattleMenu.started += instance.OnBattleUI_OpenBattleMenu;
            @BattleUI_OpenBattleMenu.performed += instance.OnBattleUI_OpenBattleMenu;
            @BattleUI_OpenBattleMenu.canceled += instance.OnBattleUI_OpenBattleMenu;
            @BattleUI_CloseBattleMenu.started += instance.OnBattleUI_CloseBattleMenu;
            @BattleUI_CloseBattleMenu.performed += instance.OnBattleUI_CloseBattleMenu;
            @BattleUI_CloseBattleMenu.canceled += instance.OnBattleUI_CloseBattleMenu;
            @BattleUI_BattleMenuShortcutPause.started += instance.OnBattleUI_BattleMenuShortcutPause;
            @BattleUI_BattleMenuShortcutPause.performed += instance.OnBattleUI_BattleMenuShortcutPause;
            @BattleUI_BattleMenuShortcutPause.canceled += instance.OnBattleUI_BattleMenuShortcutPause;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="BattleUIActionsActions" />
        private void UnregisterCallbacks(IBattleUIActionsActions instance)
        {
            @BattleUI_ClickEastButton.started -= instance.OnBattleUI_ClickEastButton;
            @BattleUI_ClickEastButton.performed -= instance.OnBattleUI_ClickEastButton;
            @BattleUI_ClickEastButton.canceled -= instance.OnBattleUI_ClickEastButton;
            @BattleUI_ClickWestButton.started -= instance.OnBattleUI_ClickWestButton;
            @BattleUI_ClickWestButton.performed -= instance.OnBattleUI_ClickWestButton;
            @BattleUI_ClickWestButton.canceled -= instance.OnBattleUI_ClickWestButton;
            @BattleUI_ClickNorthButton.started -= instance.OnBattleUI_ClickNorthButton;
            @BattleUI_ClickNorthButton.performed -= instance.OnBattleUI_ClickNorthButton;
            @BattleUI_ClickNorthButton.canceled -= instance.OnBattleUI_ClickNorthButton;
            @BattleUI_ClickSouthButton.started -= instance.OnBattleUI_ClickSouthButton;
            @BattleUI_ClickSouthButton.performed -= instance.OnBattleUI_ClickSouthButton;
            @BattleUI_ClickSouthButton.canceled -= instance.OnBattleUI_ClickSouthButton;
            @BattleUI_CloseMoveMenu.started -= instance.OnBattleUI_CloseMoveMenu;
            @BattleUI_CloseMoveMenu.performed -= instance.OnBattleUI_CloseMoveMenu;
            @BattleUI_CloseMoveMenu.canceled -= instance.OnBattleUI_CloseMoveMenu;
            @BattleUI_NextMove.started -= instance.OnBattleUI_NextMove;
            @BattleUI_NextMove.performed -= instance.OnBattleUI_NextMove;
            @BattleUI_NextMove.canceled -= instance.OnBattleUI_NextMove;
            @BattleUI_OpenBattleMenu.started -= instance.OnBattleUI_OpenBattleMenu;
            @BattleUI_OpenBattleMenu.performed -= instance.OnBattleUI_OpenBattleMenu;
            @BattleUI_OpenBattleMenu.canceled -= instance.OnBattleUI_OpenBattleMenu;
            @BattleUI_CloseBattleMenu.started -= instance.OnBattleUI_CloseBattleMenu;
            @BattleUI_CloseBattleMenu.performed -= instance.OnBattleUI_CloseBattleMenu;
            @BattleUI_CloseBattleMenu.canceled -= instance.OnBattleUI_CloseBattleMenu;
            @BattleUI_BattleMenuShortcutPause.started -= instance.OnBattleUI_BattleMenuShortcutPause;
            @BattleUI_BattleMenuShortcutPause.performed -= instance.OnBattleUI_BattleMenuShortcutPause;
            @BattleUI_BattleMenuShortcutPause.canceled -= instance.OnBattleUI_BattleMenuShortcutPause;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="BattleUIActionsActions.UnregisterCallbacks(IBattleUIActionsActions)" />.
        /// </summary>
        /// <seealso cref="BattleUIActionsActions.UnregisterCallbacks(IBattleUIActionsActions)" />
        public void RemoveCallbacks(IBattleUIActionsActions instance)
        {
            if (m_Wrapper.m_BattleUIActionsActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="BattleUIActionsActions.AddCallbacks(IBattleUIActionsActions)" />
        /// <seealso cref="BattleUIActionsActions.RemoveCallbacks(IBattleUIActionsActions)" />
        /// <seealso cref="BattleUIActionsActions.UnregisterCallbacks(IBattleUIActionsActions)" />
        public void SetCallbacks(IBattleUIActionsActions instance)
        {
            foreach (var item in m_Wrapper.m_BattleUIActionsActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_BattleUIActionsActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="BattleUIActionsActions" /> instance referencing this action map.
    /// </summary>
    public BattleUIActionsActions @BattleUIActions => new BattleUIActionsActions(this);
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "BattleActions" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="BattleActionsActions.AddCallbacks(IBattleActionsActions)" />
    /// <seealso cref="BattleActionsActions.RemoveCallbacks(IBattleActionsActions)" />
    public interface IBattleActionsActions
    {
        /// <summary>
        /// Method invoked when associated input action "Move" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnMove(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Pass" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnPass(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Shoot" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnShoot(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Change" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnChange(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Dribble" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnDribble(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Block" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnBlock(InputAction.CallbackContext context);
    }
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "BattleUIActions" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="BattleUIActionsActions.AddCallbacks(IBattleUIActionsActions)" />
    /// <seealso cref="BattleUIActionsActions.RemoveCallbacks(IBattleUIActionsActions)" />
    public interface IBattleUIActionsActions
    {
        /// <summary>
        /// Method invoked when associated input action "BattleUI_ClickEastButton" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnBattleUI_ClickEastButton(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "BattleUI_ClickWestButton" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnBattleUI_ClickWestButton(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "BattleUI_ClickNorthButton" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnBattleUI_ClickNorthButton(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "BattleUI_ClickSouthButton" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnBattleUI_ClickSouthButton(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "BattleUI_CloseMoveMenu" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnBattleUI_CloseMoveMenu(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "BattleUI_NextMove" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnBattleUI_NextMove(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "BattleUI_OpenBattleMenu" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnBattleUI_OpenBattleMenu(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "BattleUI_CloseBattleMenu" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnBattleUI_CloseBattleMenu(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "BattleUI_BattleMenuShortcutPause" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnBattleUI_BattleMenuShortcutPause(InputAction.CallbackContext context);
    }
}
